-- Tell copilot to assume that <Tab> has been mapped with cmp
-- vim.g.copilot_assume_mapped = true
--
-- vim.cmd('Copilot setup')
-- vim.cmd('Copilot enable')

-- require('copilot').setup({
--   panel = {
--     enabled = false,
--     -- auto_refresh = false,
--     -- keymap = {
--     --   jump_prev = "[[",
--     --   jump_next = "]]",
--     --   accept = "<CR>",
--     --   refresh = "gr",
--     --   open = "<M-CR>"
--     -- },
--     -- layout = {
--     --   position = "bottom", -- | top | left | right
--     --   ratio = 0.4
--     -- },
--   },
--   suggestion = {
--     enabled = false,
--     -- auto_trigger = false,
--     -- debounce = 75,
--     -- keymap = {
--     --   accept = "<M-l>",
--     --   accept_word = false,
--     --   accept_line = false,
--     --   next = "<M-]>",
--     --   prev = "<M-[>",
--     --   dismiss = "<C-]>",
--     -- },
--   },
--   filetypes = {
--     yaml = false,
--     markdown = false,
--     help = false,
--     gitcommit = false,
--     gitrebase = false,
--     hgcommit = false,
--     svn = false,
--     cvs = false,
--     ["."] = false,
--   },
--   copilot_node_command = 'node', -- Node.js version must be > 16.x
--   server_opts_overrides = {},
-- })
--
-- vim.cmd("Copilot auth")
--
-- require("copilot_cmp").setup()
