vim.cmd('set background=dark')
vim.cmd("let g:gruvbox_material_background='hard'")
vim.cmd("let g:gruvbox_material_transparent_background='2'")
vim.cmd("let g:gruvbox_material_better_performance='1'")
vim.cmd('colorscheme gruvbox-material')
