-- Map Modes
-- n = Normal
-- v = Visual and Select
-- s = Select
-- x = Visual
-- o = Operator-pending
-- i = Insert
-- l = Insert, Command-line, Lang-Arg
-- c = Command-line
-- t = Terminal
--
return { 'n', 'v', 's', 'x', 'o', 'i', 'l', 'c', 't' }
